### ISSUE TITLE
Cannot download test sets (CommandException)

### ISSUE THREAD

**Issue by j0ma** [turkic-interlingua/til-mt#4]
Hi and thank you for a very interesting resource!

I tried downloading the Turkish and Uzbek test sets, both in-domain and X-WMT, but seem to be encountering an error related to Google Drive:

```
$ python download_data.py --source_language en --target_language tr --split test
Downloading bible test files...
CommandException: No URLs matched: gs://til-corpus/corpus/test/bible/en-tr
CommandException: 1 file/object could not be transferred.
Downloading ted talk test files...
CommandException: No URLs matched: gs://til-corpus/corpus/test/ted/en-tr
CommandException: 1 file/object could not be transferred.
Downloading x-wmt test files...
CommandException: No URLs matched: gs://til-corpus/corpus/test/x-wmt/en-tr
CommandException: 1 file/object could not be transferred.
```
This results in the following empty directory structure:

```
$ tree data
data
└── en-tr
    └── test
        ├── bible
        ├── ted
        └── x-wmt
```
For what it's worth, downloading training data works just fine:

```
$ python download_data.py --source_language en --target_language tr --split train
Downloading train files...
Copying gs://til-corpus/corpus/train/en-tr/en-tr.en...
Copying gs://til-corpus/corpus/train/en-tr/en-tr.tr...                          
[  3.8 GiB]   3% Done  11.9 MiB/s ETA 00:05:10   
```

Any idea what could be causing this issue? Have the `gs://...` identifiers changed perhaps?

**Comment by j0ma** [comment]
Friendly ping @turkicinterlingua :) Happy new year!

**Comment by mirzakhalov** [comment]
Hi there! Thank you for opening this issue! Let me check on this

**Comment by mirzakhalov** [comment]
Ah looks like the script had the old path! The new commit should have fixed the issue. Let me know if it works now

**Comment by j0ma** [comment]
Thanks a lot, seems like it was a simple fix! Just to be clear -- if I have a download folder like

```
├── dev
│   └── en-uz
│       ├── en-uz.en
│       └── en-uz.uz
├── test
│   └── en-uz
│       ├── en-uz.en
│       └── en-uz.uz
└── train
    └── en-uz
        ├── en-uz.en
        └── en-uz.uz
```
 then the `test` and `dev` folders contain the data for the in-domain evaluation sets as described in Section 3.1.1. of the [multilingual paper](https://github.com/turkic-interlingua/til-mt/tree/master/replicate_results/multilingual_paper), correct? 

Thanks again!

**Comment by mirzakhalov** [comment]
Yes! This specific path includes the in-domain dev and test sets for the paper you mentioned. Out of domain ones are in the x-wmt section of the repo
